#!/usr/bin/env bash
#
# launsh - A collection of actions to drive daily computing
#
# SPDX-License-Identifier: BSD-3-Clause
# Author: Björn Busse <bj.rn@baerlin.eu>
#
# Dependencies: bash, curl, vju
# Individual modules may have further dependencies
#

LAUNSH_OPEN="${LAUNSH_OPEN:=xdg}"
MODULE_PATH="${HOME}/.local/share/launsh/modules"
SCRIPT_NAME="$(basename "${0}")"
log_level=info

LAUNSH_SEND_NOTIFICATION=1

# Source all .sh modules in the MODULE_PATH directory
if [ -d "${MODULE_PATH}" ]; then
    for module in "${MODULE_PATH}"/*.sh; do
        [ -f "${module}" ] && source "${module}"
    done
fi

# Aliases setup
LAUNSH_ALIASES=(
    'lo="launsh application"'
    'la="launsh auth onelogin"'
    'lcmd="launsh commands"'
    'ldc="launsh open-document Documents ~/Documents"'
    'ldw="launsh open-document Downloads ~/Downloads"'
    'gcs="launsh gh-copilot-suggest"'
    'gce="launsh gh-copilot-explain"'
    'lh="launsh histories"'
    'lpw="launsh pass"'
    'lrss="launsh rss ${LAUNSH_DB_FILE_RSS} feeds entries"'
    'lssm="launsh ssm"'
    'ltv="launsh tv 📺 https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/clean/clean_tv.m3u"'
    'li="launsh view-image "img" ~/Pictures"'
    'lw="launsh weather --width 1400 --height 1200 --monospace"'
)

function main() {
    local action
    action="${1}"

    case "${action}" in
        allthethings) allthethings "${@}" ;;
        help) show_help ;;
        application|open) open "${@}" ;;
        bluetooth) bt_toggle_connect_device "${@}" ;;
        commands) commands "${@}" ;;
        histories) histories "${@}" ;;
        mpv-mute|mpv-playlist-next|mpv-playlist-prev|mpv-start) mpv_command "${@}" ;;
        open-document|view-image) open_document "${@}" ;;
        pass) clip_pass "${@}" ;;
        tv) tv "${@}" ;;
        rss) rss "${@}" ;;
        search-tube) search_tube "${@}" ;;
        search-web) search_web "${@}" ;;
        ssm) ssm "${@}" ;;
        vm-start) start_vm "${@}" ;;
        vm-connect) libvirt_vm_connect_vnc "${@}" ;;
        wifi-connect) wifi_connect "${@}" ;;
        wifi-scan) wifi_scan "${@}" ;;
        weather) weather "${@}" ;;
        install-aliases) install_aliases ;;
        maintenance) maintenance "${@}" ;;
        list-modules) list_modules ;;
        *)
            echo "Unknown action: ${action}"
            show_help
            ;;
    esac
}

main "${@}"
